language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t prabinv/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true prabinv/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-312974876853"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY

